// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar3 from "./_componets/HomePage/navbar2/navbar3/NavBar3";
import BodyWrapper from "./_componets/bodywrapper/BodyWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const fontClass = `${geistSans.variable} ${geistMono.variable}`;

  return (
    <html lang="en">
      <BodyWrapper fontClass={fontClass}>
        <Navbar3 />
        {children}
      </BodyWrapper>
    </html>
  );
}
